# Generated by Django 5.0.2 on 2025-08-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
    ]
