# Generated by Django 5.2.3 on 2025-08-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_orderitem_orderitemextra'),
        ('products', '0002_ingredient_alter_product_image_productingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('was_default', models.BooleanField(default=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.orderitem')),
            ],
            options={
                'verbose_name': 'Ingrediente de Item',
                'verbose_name_plural': 'Ingredientes de Items',
                'unique_together': {('order_item', 'ingredient')},
            },
        ),
    ]
